services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    image: recallcode-client
    container_name: recallcode-client
    ports: 
    - "127.0.0.1:5173:80" 
    depends_on:
      - backend
    networks:
      - recallcode-network  

  docs:
    build:
      context: ./RecallCode-Docs
      dockerfile: Dockerfile
    image: recallcode-docs  
    container_name: recallcode-docs
    ports: 
    - "127.0.0.1:5174:80"
    depends_on:
      - backend
    networks:
      - recallcode-network     

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: recallcode-backend
    image: recallcode-backend
    env_file:
      - ./Server/.env
    expose:
      - "7000"
    depends_on:
      - mongo
    networks:
      - recallcode-network

  mongo:
    image: mongo
    container_name: recallcode-mongo
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - recallcode-network

volumes:
  mongo_data:

networks:
  recallcode-network:
    driver: bridge